"""
database.py — SQLite CRM + invite-token management
All data stored in assessments.db next to this file.

Tables:
  tokens      — invite links generated by the admin (one per client)
  assessments — completed assessment records (timestamped)
"""

import json
import secrets
import sqlite3
from datetime import datetime
from pathlib import Path

DB_PATH = Path(__file__).parent / "assessments.db"


# ── Connection ─────────────────────────────────────────────────────────────────
def _conn():
    c = sqlite3.connect(DB_PATH, check_same_thread=False)
    c.row_factory = sqlite3.Row
    return c


# ── Schema ─────────────────────────────────────────────────────────────────────
def init_db():
    """Create tables if they don't already exist. Safe to call on every startup."""
    with _conn() as c:
        c.execute("""
            CREATE TABLE IF NOT EXISTS tokens (
                id           INTEGER PRIMARY KEY AUTOINCREMENT,
                token        TEXT    UNIQUE NOT NULL,
                client_name  TEXT    DEFAULT '',
                client_email TEXT    DEFAULT '',
                notes        TEXT    DEFAULT '',
                created_at   TEXT    NOT NULL,
                used_at      TEXT,
                is_used      INTEGER DEFAULT 0
            )
        """)
        c.execute("""
            CREATE TABLE IF NOT EXISTS assessments (
                id                INTEGER PRIMARY KEY AUTOINCREMENT,
                token             TEXT,
                client_name       TEXT,
                client_surname    TEXT    DEFAULT '',
                client_business   TEXT,
                client_email      TEXT,
                business_size     TEXT,
                industry          TEXT    DEFAULT '',
                service_product   TEXT    DEFAULT '',
                business_age      TEXT    DEFAULT '',
                completed_at      TEXT,
                avg_score         REAL,
                maturity_level    TEXT,
                total_score       INTEGER,
                p1_avg  REAL, p2_avg REAL, p3_avg REAL, p4_avg REAL,
                p5_avg  REAL, p6_avg REAL, p7_avg REAL,
                scores_json       TEXT
            )
        """)
        c.commit()

    # ── Migrate existing databases (add new columns if missing) ────────────────
    _migrate()


def _migrate():
    """Add any columns introduced after initial deployment."""
    new_cols = [
        ("client_surname",  "TEXT DEFAULT ''"),
        ("industry",        "TEXT DEFAULT ''"),
        ("service_product", "TEXT DEFAULT ''"),
        ("business_age",    "TEXT DEFAULT ''"),
    ]
    with _conn() as c:
        for col, col_def in new_cols:
            try:
                c.execute(f"ALTER TABLE assessments ADD COLUMN {col} {col_def}")
                c.commit()
            except sqlite3.OperationalError:
                pass  # column already exists — safe to ignore


# ── Token management ───────────────────────────────────────────────────────────
def generate_token(client_name: str = "", client_email: str = "", notes: str = "") -> str:
    """Create a new single-use invite token and return it."""
    token = secrets.token_urlsafe(20)
    with _conn() as c:
        c.execute(
            "INSERT INTO tokens (token, client_name, client_email, notes, created_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (token, client_name.strip(), client_email.strip(),
             notes.strip(), _now()),
        )
        c.commit()
    return token


def is_token_valid(token: str) -> bool:
    """True if token exists and has not yet been used."""
    with _conn() as c:
        row = c.execute(
            "SELECT is_used FROM tokens WHERE token = ?", (token,)
        ).fetchone()
    return bool(row and row["is_used"] == 0)


def get_token_info(token: str) -> dict | None:
    """Return full token row as dict, or None if not found."""
    with _conn() as c:
        row = c.execute(
            "SELECT * FROM tokens WHERE token = ?", (token,)
        ).fetchone()
    return dict(row) if row else None


def mark_token_used(token: str):
    with _conn() as c:
        c.execute(
            "UPDATE tokens SET is_used = 1, used_at = ? WHERE token = ?",
            (_now(), token),
        )
        c.commit()


def get_all_tokens() -> list[dict]:
    with _conn() as c:
        rows = c.execute(
            "SELECT * FROM tokens ORDER BY created_at DESC"
        ).fetchall()
    return [dict(r) for r in rows]


def delete_token(token: str):
    with _conn() as c:
        c.execute("DELETE FROM tokens WHERE token = ?", (token,))
        c.commit()


# ── Assessment records ─────────────────────────────────────────────────────────
def save_assessment(token: str, client_info: dict, results: dict,
                    raw_scores: dict | None = None):
    """
    Persist a completed assessment and mark the token as used.

    client_info keys:
        name, surname, business, email, size, industry, service_product, business_age

    results:
        output of data.compute_results()

    raw_scores:
        {pillar_id: [q1_score, q2_score, q3_score, q4_score], ...}
        Pass st.session_state collect_scores() output for full per-question storage.
    """
    pa = results["pillar_avgs"]

    # Build the full scores JSON — pillar averages + individual question scores
    scores_payload = {
        "pillar_avgs":    {str(k): v for k, v in pa.items()},
        "pillar_totals":  {str(k): v for k, v in results["pillar_totals"].items()},
    }
    if raw_scores:
        # Store as {"p1": [s1,s2,s3,s4], "p2": [...], ...}
        scores_payload["question_scores"] = {
            str(pid): scores for pid, scores in raw_scores.items()
        }

    with _conn() as c:
        c.execute("""
            INSERT INTO assessments (
                token,
                client_name, client_surname, client_business, client_email,
                business_size, industry, service_product, business_age,
                completed_at, avg_score, maturity_level, total_score,
                p1_avg, p2_avg, p3_avg, p4_avg, p5_avg, p6_avg, p7_avg,
                scores_json
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            token,
            client_info.get("name", ""),
            client_info.get("surname", ""),
            client_info.get("business", ""),
            client_info.get("email", ""),
            client_info.get("size", ""),
            client_info.get("industry", ""),
            client_info.get("service_product", ""),
            client_info.get("business_age", ""),
            _now(),
            results["avg_score"],
            results["maturity"]["label"],
            results["total_score"],
            pa.get(1, 0), pa.get(2, 0), pa.get(3, 0), pa.get(4, 0),
            pa.get(5, 0), pa.get(6, 0), pa.get(7, 0),
            json.dumps(scores_payload),
        ))
        c.commit()

    if token and token != "no-token":
        mark_token_used(token)


def get_all_assessments() -> list[dict]:
    with _conn() as c:
        rows = c.execute(
            "SELECT * FROM assessments ORDER BY completed_at DESC"
        ).fetchall()
    return [dict(r) for r in rows]


# ── Helpers ────────────────────────────────────────────────────────────────────
def _now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
